name: docs

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install latex
      run: sudo apt install -y latexmk texlive-latex-extra texlive-science texlive-lang-portuguese

    - name: Checkout submodules
      shell: bash
      run: |
        # If your submodules are configured to use SSH instead of HTTPS please uncomment the following line
        # git config --global url."https://github.com/".insteadOf "git@github.com:"
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

    - name: Give permission to execute
      run: chmod u+x *.sh

    - name: Compile exams
      run: make exams/BDAD_exams.pdf

    - name: Upload exams
      uses: actions/upload-artifact@v2
      with:
        name: BDAD_exams.pdf
        path: exams/BDAD_exams.pdf

    - name: Compile book
      run: make book/BDAD_book.pdf

    - name: Upload book
      uses: actions/upload-artifact@v2
      with:
        name: BDAD_book.pdf
        path: book/BDAD_book.pdf
